---
baseURL: https://dev.wmyeah.com
languageCode: en-us
title: WMYeah
theme: piko
paginate: "20"
copyright: A template by [Heksagon](https://www.heksagon.net "Your most friendly developer")
googleAnalytics: "G-RDBNJJYEQ4" # Enter Google Analytics ie. UA-012345678-9
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
outputs:
  home:
  - HTML
  - RSS
  - JSON
minify:
  disableCSS: false
  disableHTML: false
  disableJS: false
  disableJSON: false
  disableSVG: false
  disableXML: false
  minifyOutput: true
  tdewolff:
    html:
      keepWhitespace: false

params:
  analytics:
    google:
      SiteVerificationTag: # Google Site Verification
    yandex:
      SiteVerificationTag: # Yandex Site Verification
    bing:
      SiteVerificationTag: # Bing Site Verification
  env: production
  author: WMYeah
  description: Build Dream
  math: false
  images:
  - "/uploads/og.webp"
  label:
    title: _WMYeah_
    text: Welcome to Piko
    lightNavIcon: /uploads/sun.svg
    darkNavIcon: /uploads/zap.svg
    iconHeight: "35"
    iconWIdth: "35"
  comments: true
  mainSections:
  - blog
  ShowShareButtons: true
  ShowCodeCopyButtons: true
  ShowRelated: true
  CookieNotice: We use cookies to improve your experience on our site and to show
    you relevant advertising.
  CookieLink: /legal/privacy/#cookies-and-web-beacons
  CookieButton: Cookies Policy
  disableAnchoredHeadings: false
  contactFormAction: https://formsubmit.io/send/7ff640f5-d625-4ab4-a4b5-84e9c1c3f705 # Get link from https://formsubmit.io or https://fabform.io
  assets:
    disableFingerprinting: false
    favicon: /uploads/zap.svg
    favicon16x16: /uploads/zap.svg
    favicon32x32: /uploads/zap.svg
    apple_touch_icon: /uploads/zap.svg
    safari_pinned_tab: /uploads/zap.svg
  ShowReadingTime: true
  ShowBreadCrumbs: true
  homepage:
    # Hero Section
    disableHeroSection: false
    heroUpperTitle: 
    heroTitle: Run Dream
    heroDescription: Let's chase our dreams together
    heroCTAPrimaryText: Blog
    heroCTAPrimaryUrl: "/blog/"
    heroCTASecondaryText: Contact Me
    heroCTASecondaryUrl: "/contact/"
    heroBackgroundImage: "/uploads/portfolio-1.webp"
    # Blog Section
    disableBlogSection: false
    blogTitle: Latest Posts
    blogDescription: This is my latest blog posts
    seeMoreText: More Posts
    # About Section    
    disableAboutSection: false
    aboutTitle: About
    aboutDescription: Just Me
    aboutImgUrl: "/uploads/self.webp"
    aboutContent: |
      白日依山尽，
      The bright sun leans on the mountains at dusk,
      黄河入海流。
      The Yellow River flows into the sea.
      欲穷千里目，
      If you yearn to gaze as far as the thousand-mile horizon,
      更上一层楼。
      Climb one more story.
    # Portfolio Section
    disablePortfolioSection: false
    portfolioTitle: Cases
    portfolioDescription: a some ....
    portfolio:
    - imageUrl: https://github-readme-stats.vercel.app/api/pin/?username=george012&repo=gtbox&title_color=fff00&icon_color=f9f9f9&text_color=9f9f9f&bg_color=151515
      alt: Custom Go Application Develop Tools  # image alt for better SEO
      description: Custom Go Application Develop Tools.
      websiteUrl: https://github.com/george012/gtbox
    - imageUrl: https://github-readme-stats.vercel.app/api/pin/?username=george012&repo=one_key_install_core-geth&title_color=fff00&icon_color=f8f8f8&text_color=9f9f9f&bg_color=151515
      alt: One-click installation of core-geth  # image alt for better SEO
      description: One-click installation of core-geth.
      websiteUrl: https://github.com/george012/one_key_install_core-geth
    - imageUrl: https://github-readme-stats.vercel.app/api/pin/?username=george012&repo=libhv-build&title_color=fff00&icon_color=f8f8f8&text_color=9f9f9f&bg_color=151515
      alt: Auto Buid libhv  # image alt for better SEO
      description: Auto Buid libhv.
      websiteUrl: https://github.com/george012/gt_script
    - imageUrl: https://github-readme-stats.vercel.app/api/pin/?username=george012&repo=gt_script&title_color=fff00&icon_color=f8f8f8&text_color=9f9f9f&bg_color=151515
      alt: Commonly used Shell scripts  # image alt for better SEO
      description: Commonly used Shell scripts.
      websiteUrl: https://github.com/george012/gt_script
  # Search Options (https://fusejs.io/)
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: "0"
    distance: "1000"
    threshold: "0.4"
    minMatchCharLength: "0"
    keys:
    - title
    - permalink
    - summary
    - content
  plugins:
    css:
    - link: plugins/css/pico.min.css
    js:
    - link: plugins/js/feather.min.js
menus:
  main: # Main Menu
  - name: Blog
    title: Blog
    pre: pen-tool
    url: "/blog"
    weight: "20"
  - name: Categories
    title: Categories
    pre: pen-tool
    pre: categories
    url: "/categories"
    weight: "20"
  - name: Search
    title: Search
    pre: search
    url: "/search"
    weight: "30"
  - name: Contact
    title: Contact
    pre: mail
    url: "/contact"
    weight: "40"
  - name: Github
    title: 
    pre: github
    url: https://github.com/george012
    weight: "50"
  search: # Search page's quick links
  - name: Categories
    title: Categories
    url: "/categories"
    weight: "10"
  - name: Archives
    title: Archives
    url: "/archives"
    weight: "20"
  - name: Tags
    title: Tags
    url: "/tags"
    weight: "30"
