baseURL: https://www.wmyeah.com
title: WMYeah
languageCode: en
DefaultContentLanguage: cn
preserveTaxonomyNames: true
theme: hugo.386

params:
  mainpagetitle: WMYeah
  mainpagesubtitle: Buid Your Dream
  mainpagedesc: This theme is the Hugo port of the BOOTSTRA.386 theme for a cool
    retro look on your blog. Check the links below to access the posts.

  showhugo: true
  copyright:
      name: WMYeah
      url: http://www.wmyeah.com
      prefix: "[hugo.386 theme by Max le Fou](https://gitlab.com/maxlefou/hugo.386)"
      suffix: Example site
  
  loadfastload: true
  loadspeedfactor: 0.5
  loadonepass: true


menu:
  main:
    - identifier: posts
      name: posts
      url: /posts/
      weight: 20
    - identifier: about
      name: about
      url: /about/
      weight: 10


taxonomies:
  category: categories
  tag: tags
